### PR TITLE
Reviewed tutorials

### PR DESCRIPTION
**Pull request by t4sk**
This PR makes several changes summarised below

## LIGHTNING-01-peers
- Add note to create or unlock an lightning wallet before making a rpc call to getinfo
- Add link to README.bitcoin and README.litecoin

## LIGHTNING-02-connect
- Fix command to connect to peer

## LIGHTNING-03-channels
- Replace pubkeys with variable

### CODE REVIEW

**Review by kilrau — APPROVED** [review]
All of them make sense (mostly putting keys in variables to not blow up commands). README only minor spacing fixes.

**Comment by kozyilmaz** [comment]
Hi @t4sk, due to the previous PR merge there are some conflicting changes in yours. Can you please revise? Thanks!

**Comment by kozyilmaz** [comment]
@t4sk There are erroneous text in LIGHTNING-01-peers.md that are left from the merge conflict (look for `<<<<<<< HEAD`,` >>>>>>> Review LIGHTNING-01-peers`)

**Comment by t4sk** [comment]
Oops, sorry. Fixed

**Pull request merged**
