### PR TITLE
Minor edits and notes

### PR DESCRIPTION
**Pull request by sangaman**
These are a few minor improvements to the steps in this guide that I thought of while going through them.

### CODE REVIEW

**Review by kilrau — APPROVED** [review]
Looks, good please compare with @t4sk  s changes and combine

**Review by kilrau — COMMENTED** [review]
Why hide this?

**Comment by sangaman** [comment]
@kilrau Hide the `listpeers` output you mean? If you follow the steps in the guide and run lnd with the `nobootstrap` option, listpeers will return an empty array until you manually connect to a peer (or have a peer manually connect with you). I was just trying to make it consistent with what one would see if they followed this step by step.

**Comment by kilrau** [comment]
Alright, that makes sense.



On Daniel McNally <notifications@github.com>, Jan 15, 2018 12:35 PM wrote:

@kilrau<https://github.com/kilrau> Hide the listpeers output you mean? If you follow the steps in the guide and run lnd with the nobootstrap option, listpeers will return an empty array until you manually connect to a peer (or have a peer manually connect with you). I was just trying to make it consistent with what one would see if they followed this step by step.

**Comment by kozyilmaz** [comment]
Looks good!

**Pull request merged**
